### ISSUE TITLE
No attribute white

### ISSUE THREAD

**Issue by soslug** [benleb/PyGlow#13]
Hi Benleb,

I have been working with your repository on my Pi 2 after trying Boeeerb and Gadgetoid to work on it has taken much time mainly because I class myself just above a noob.

Anyways it looks like your readme helped me a lot along with the forums and might suggest a re-edit or additions to your readme so other might benefit.

There should be many would be programmers who would be delighted to get PiGlow to work on any model of RPi and for any python versions.

First I had to get PiGlow to work from a virgin install of "Raspbian" first problem is that does not work straight from the box so to speak, although it does in scratch provided rpi-config correctly set. But following your directions and this blog by Rob Sender I finally got it two work.

http://blog.robseder.com/2015/04/12/getting-a-piglow-to-work-with-a-raspberry-pi-2

python does require some additional modules installed, these being correctly identified in your Readme:-

sudo apt-get install python-smbus
sudo apt-get install python-psutil

However Python3 does not share the same modules as those in Python 2.7 so you also need the following modules installed.

sudo apt-get install python3-smbus
sudo apt-get install python3-psutil

Perhaps you think it obvious but such things put off newbies and noobs and many Pros as well, from investigating further when the place they install from a given repository leaves huge gaps. (Sorry not trying to be condescending just came out that way)

Then there is this annoying sn3218 issue, no mention is made of this in your readme so I had to find the info from elsewhere.

Here is what you need to fix this issue and strongly suggest you might want to include this documentation in the Readme.

sudo apt-get install python-pip
sudo pip install sn3218

This installs the required module for python to use, at least this is necessary at least on RPi 2 and RPi 3 I have not tried this yet on B+ etc or other variants.

I have now ported over all the example code from "Boeeerb" repository and modified most so they can run either with python 2 or python 3, the clock.py I cheated a bit and edited some of the print and stdout statements that display the clock to the screen from the "bin_clock.py". But both now work with both python variants.

I have come across one example code as yet I cannot fix and believe the problem may reside in PyGlow.py itself but together with my lack of experience and code knowledge I cannot resolve the problem or suggest how to correct it. Looking at PyGlow.py and word searching for "white" which I can see they are in the code so among the list of colours. Why it does not work, I cannot fathom.

By the way the export string in .bashrc worked a treat plus made perfect sense however, it did not fix this problem perhaps you could take a look

Traceback (most recent call last):
  File "cycle.py", line 13, in <module>
    pyglow.white(10)
AttributeError: PyGlow instance has no attribute 'white'

cycle code
###### 
## 
###### 

from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

while True:
    pyglow.white(10)
    sleep(0.1)
    pyglow.blue(10)
    sleep(0.1)
    pyglow.green(10)
    sleep(0.1)
    pyglow.yellow(10)
    sleep(0.1)
    pyglow.orange(10)
    sleep(0.1)
    pyglow.red(10)
    sleep(0.1)
    pyglow.red(0)
    sleep(0.1)
    pyglow.orange(0)
    sleep(0.1)
    pyglow.yellow(0)
    sleep(0.1)

If you would like the other code ports to include them please let me know

**Comment by soslug** [comment]
Never mind found the error after all staring me in the face the whole time. 

##################################################

## Switch each colour on in sequence on and off

## 

## Example by Jason - @Boeeerb

##################################################

from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

while True:
    pyglow.color("white", 10)
    sleep(0.1)
    pyglow.color("blue", 10)
    sleep(0.1)
    pyglow.color("green", 10)
    sleep(0.1)
    pyglow.color("yellow", 10)
    sleep(0.1)
    pyglow.color("orange", 10)
    sleep(0.1)
    pyglow.color("red", 10)
    sleep(0.1)
    pyglow.color("red", 0)
    sleep(0.1)
    pyglow.color("orange", 0)
    sleep(0.1)
    pyglow.color("yellow", 0)
    sleep(0.1)
    pyglow.color("green", 0)
    sleep(0.1)
    pyglow.color("blue", 0)
    sleep(0.1)
    pyglow.color("white", 0)
    sleep(0.1)

If you intend to use the above code please remember to indent after

while True:

**Comment by benleb** [comment]
seems solved :) I have no rpi3 to test this issue but if you have worked out all problems, maybe you can create a pull request?
